# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Snapshot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Create Archive
      steps:
        - run: |
            mkdir -p ${{ github.workspace }}/artifact
            cp ${{ github.workspace }}/target/*-jar-with-dependencies.jar ${{ github.workspace }}/artifact/covid-stats-pt.jar
            cp ${{ github.workspace }}/config.properties.sample ${{ github.workspace }}/artifact/config.properties
        - uses: actions/upload-artifact@v2
          with:
            name: covid-stats-pt.zip
            path: ${{ github.workspace }}/artifact/*