# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Snapshot

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]

    runs-on: ${{ matrix.os }}

    name: COVID Stats PT - Build (${{ matrix.os }})

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify

  package:
    runs-on: 'ubuntu-latest'

    name: COVID Stats PT - Release

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir snapshot && cp target/*.jar snapshot
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: snapshot
